name: deb-build (Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: debian:latest
    permissions:
      contents: write # to upload artifacts
    steps:
      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          apt update
          apt install git g++ make libc6-dev cmake libpng-dev libjpeg-dev libgl1-mesa-dev libsqlite3-dev libogg-dev libvorbis-dev libopenal-dev libcurl4-gnutls-dev libfreetype6-dev zlib1g-dev libgmp-dev libjsoncpp-dev libzstd-dev libluajit-5.1-dev gettext libsdl2-dev -y
      
      - name: Build Debian package
        run: |
          cmake . -DRUN_IN_PLACE=TRUE -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: Fix File Permissions
        run: chown -R $USER:$USER bin/

      - name: Pack executable File
        run: |
          sudo apt-get install -y zip
          mkdir -p deb_package/
          cp -r bin/* deb_package/
          cd deb_package/
          zip -r ../luanti-deb-package.zip ./*

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: luanti-deb-package
          path: luanti-deb-package.zip