name: deb-build (Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: debian:latest
    permissions:
      contents: write # to upload artifacts
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          docker-images: true
      - name: Install build dependencies
        run: |
          apt-get update
          sudo apt install git g++ make libc6-dev cmake libpng-dev libjpeg-dev libgl1-mesa-dev libsqlite3-dev libogg-dev libvorbis-dev libopenal-dev libcurl4-gnutls-dev libfreetype6-dev zlib1g-dev libgmp-dev libjsoncpp-dev libzstd-dev libluajit-5.1-dev gettext libsdl2-dev
      - name: Build Debian package
        run: |
          cmake . -DRUN_IN_PLACE=TRUE -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)

      - name: Fix File Permissions
        run: sudo chown -R $USER:$USER bin/

      - name: Upload Debian package
        uses: actions/upload-artifact@v4
        with:
          name: luanti-deb-package
          path: deb/